apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwkproject-dep
  namespace: dwk-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwkproject
  template:
    metadata:
      labels:
        app: dwkproject
    spec:
      volumes:
        - name: dwkproject-vol
          persistentVolumeClaim:
            claimName: dwkproject-claim
      containers:
        - name: dwkproject
          image: FRONTEND_IMAGE
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
          volumeMounts:
            - name: dwkproject-vol
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "8080"
