---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: dwk-exercises
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAuYw6LZy4NOQSqLoRe+0izWpve7nghHdgKO/paKXENyTWbNgNAcMIApSJOSyln6Afhb+woquPm8jYgosdl5alRIIz+fSWhipogEFaV7yS16Bvq6C3QCXGxnsn8Uv1zAy1M/Yw/TIoTttFQOVDD5iqzpjg4egkllAr4Y+1x7V963dezJZR5E8DBPqh2l83xgQrlBfaQdAeU2yI6/nb1rPb730aN2qj0rFWadfq1O3s7aiaJ3Bm2jYvNKoU62eRFuh7kIFjgwVsjJoeZAsftCA3ImHyLMjwbXRe67buoDbGWvWbP81LAm9+sNOpYw9tIKCJUZZLen1dfXRoYj0JY1Y1UBESfYggo8G6umrf/bLh0ZjvEx6DP4eBErBBl5WnMhK6AY7OY+ctWY1mUmVKt6qdK3P6reAPR04K0bwv/ektVp76HjSSRs543lUtX3pmbJ/K4Df+QjAh5hbz1Ai1huIwH4PXGDMILlorAM/yQgeyOovDiI6/dJzNYKJ2iP7vx87LVHYmkiacWbLyxTXhIEF/Il/lTzbP01uc3yLMIrG6HKnUIXjaeO9JaZXX2glT7aNdRYjK/yOCu6hQsSQFk+g6F1eue8L2NRfBmGi97rPkwIn5TVoaFvqNtnLD5uB/3ufp6xuLfBMd5qphB0/RDBR+W3mU3s7dPDDFkaiCN6y6n4sG4knl4tQkWDLwVy8ke5uPijJJVO31HoQBaq9aBCa4BISUmr2AIxwC6bdj5Fug+tRDMIunVWLCLMuA=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: dwk-exercises
