apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dwk-project

resources:
  - project-backend/manifests/analysistemplate.yaml
  - project-backend/manifests/rollout.yaml
  - project-backend/manifests/postgres.yaml
  - project-backend/manifests/sealed-secret.yaml
  - project-backend/manifests/service.yaml
  - project-backend/manifests/todocron.yaml
  - project-frontend/manifests/deployment.yaml
  - project-frontend/manifests/ingress.yaml
  - project-frontend/manifests/persistentVolumeClaim.yaml
  - project-frontend/manifests/service.yaml
  - project-broadcaster/manifests/deployment.yaml

images:
  - name: FRONTEND_IMAGE
    newName: hremonen/dwkproject-frontend:4.05
  - name: BACKEND_IMAGE
    newName: hremonen/dwkproject-backend:4.06
  - name: CRONJOB_IMAGE
    newName: hremonen/dwkproject-cron:3.03
  - name: BROADCASTER_IMAGE
    newName: hremonen/dwkproject-broadcaster:4.06
