apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwkproject-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwkproject
  template:
    metadata:
      labels:
        app: dwkproject
    spec:
      containers:
        - name: dwkproject
          image: hremonen/dwkproject:1.05
          env:
           - name: PORT
             value: "8080"