apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwkproject-claim
  namespace: dwk-project
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi