apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-exercises
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: logoutput
          image: hremonen/logoutput:4.01
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: logoutput-configmap
          volumeMounts:
            - name: logoutput-vol
              mountPath: /usr/src/app/logs
            - name: config-volume
              mountPath: /usr/src/app/config
        - name: logoutput-generator
          image: hremonen/logoutput-generator:3.02
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: logoutput-vol
              mountPath: /usr/src/app/logs
      volumes:
        - name: logoutput-vol
          persistentVolumeClaim:
            claimName: logoutput-claim
        - name: config-volume
          configMap:
            name: logoutput-configmap
