name: Project GitOps Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build Project Images
        run: |-
          docker build --build-arg PRODUCTION=true --tag "hremonen/dwkproject-frontend:$GITHUB_SHA" ./project-frontend
          docker build --build-arg PRODUCTION=true --tag "hremonen/dwkproject-backend:$GITHUB_SHA" ./project-backend
          docker build --build-arg PRODUCTION=true --tag "hremonen/dwkproject-cron:$GITHUB_SHA" ./project-cron
          docker build --build-arg PRODUCTION=true --tag "hremonen/dwkproject-broadcaster:$GITHUB_SHA" ./project-broadcaster

      - name: Push images to Docker Hub
        run: |-
          docker push "hremonen/dwkproject-frontend:$GITHUB_SHA"
          docker push "hremonen/dwkproject-backend:$GITHUB_SHA"
          docker push "hremonen/dwkproject-cron:$GITHUB_SHA"
          docker push "hremonen/dwkproject-broadcaster:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Generate Kustomization
        run: |-
          kustomize edit set namespace dwk-project
          kustomize edit set image FRONTEND_IMAGE=hremonen/dwkproject-frontend:$GITHUB_SHA
          kustomize edit set image BACKEND_IMAGE=hremonen/dwkproject-backend:$GITHUB_SHA
          kustomize edit set image CRONJOB_IMAGE=hremonen/dwkproject-cron:$GITHUB_SHA
          kustomize edit set image BROADCASTER_IMAGE=hremonen/dwkproject-broadcaster:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "project/kustomization.yaml"
          message: New version released ${{ github.sha }}
