apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwkproject-backend-dep
  namespace: dwk-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwkproject-backend
  template:
    metadata:
      labels:
        app: dwkproject-backend
    spec:
      containers:
        - name: dwkproject-backend
          image: BACKEND_IMAGE
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-db-secret
                  key: POSTGRES_PASSWORD
