apiVersion: v1
kind: Service
metadata:
  name: project-db-svc
  namespace: dwk-project
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: project-db
      protocol: TCP
  clusterIP: None
  selector:
    app: project-db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: project-db-stset
  namespace: dwk-project
spec:
  serviceName: project-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: project-db
  template:
    metadata:
      labels:
        app: project-db
    spec:
      containers:
        - name: project-db
          image: postgres:16.3-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: project-db
              containerPort: 5432
          volumeMounts:
            - name: project-db-data
              mountPath: /var/lib/postgresql/data
              subPath: project-db

  volumeClaimTemplates:
    - metadata:
        name: project-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
