---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: project-db-secret
  namespace: dwk-project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCRpFMueFIP8UkV/ixNNHAjy2MH8DTtTFcriuEqZJo7UYJUPkQi7A28Ds2YFRK7mD8PwEZ4tnb9kCLfkmXdGGHLNpx9wErMBiPx9UOnJoVPVthbSaYxcLfafF8KIXCZ+hvpzPAOs7R/QCL5CGtz4r34xQ/mcC6LG2U3vp1xxjHtV3JiUBU1snzTLNLK71FcIuRAVaj/KJti3blAdOviAN5oUJn1mM7tOLm7j88O20cvrNq7a79Nqg1AyK3Gwqz5J5QNZWxAsMK0CA4c9GaJrqdtQ04WJT7n/riHuVRkN+S/Hw95MeKgDLZdDicik1Y6hzJODFenRfsFCBxF3pF51XUySHmQQikH9GsQ1NVfYRv/PppLtRlo979tfA6nADjMDYevLkeCp6AD9hd4PHIgcFYJNXaRPWzp+8vxiX+Fl+Dp09udI5AAgVGd8IYk+WH9zUvjkcyFyW8W3dhhFVg8UvOzUyzJjZb6ILhSJt0eji2/lqESBKnR6Mv9+vicByKvWH8lZ86BJOc1vT1hx1nCjk/YEZE7FH5RAIU3gZs/dwN2BysbGhl4eWLG9karK+2gO+As5lj4JkB7HNGg0/MOFf3S+lb/GBwCB2XH4n9y90PxLbuFaaVnO71pJDGet+0TBeEC8KnWuZEJXhiqznfaLquYO6nAa5yXI2FU1y38+PjXMwqCvLozgsERVxjhLEGKV4BO9CHpoWzazAag5nyeV0tCML9XdVMV/IO2Zw9RG6gYwuevTCUcqJ/4R5c=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: project-db-secret
      namespace: dwk-project
