---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: project-db-secret
  namespace: dwk-project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB+SSXbRyBkmH2WdVSvmBTvwL+X8bbcLp9RWy46EaShgMtLrdJ3OmXrVLv8Za40EIULD4sYBSVY8ACZoWVA0ctnCbTfzrfigjYntCliSgUmg5UL/nYHCTk5C5vBoDRx1gq/5HuOasWiC3i9ysQVX0LbDhCJcZApKAjM1W+IushCTbgNa+pXT9Bl+sByEK0EhXkGr3Zsmef1/R2BUnGZzpTCeO/jP9XmskUpGKGWgbgfcLWQKTA5Eqa0YdC4Z6UrX8pBHPOO/6hdA/kXgnT/r+4+FiNFTDGtqyg/apWosZpuAOgzu1mN30Wur74S5GUa45UIgDRTsf3vRIcJ6HQK8l626fO81E88vevzrJ0wFhc90JexE1obisRu8bdLWEg8tU8q5i83jraCwUb/Ks57qUS97o2Dqysvd3voQHs7QhC1l6pQ3GBGvgwrh4dkS4TS9B5ApYiMmu4Uw4lwXkY9tsp06rx6xxx93s9cxYa4fmxsAJ4Y/hryW6Cg2ijMItJFgfyZzhxCskCLyN4fUuYqChOORxB5w2EZFCRjwCIynGcT4vJ4njjj0Zx6FaRPFQ8YjN+5d3JzHWgbevoiodD7WRs3j4zfXAXBzzna0wJjGaBd8nEn796uDmYDq0PvtSa9H8QISuEZBrda7SA6fFeec018ra0ijwoi+wIFqNxkUSeYlGLEUrALcB9XdiPY2sqaZ4JmPeMT2Yuh0H2snMBtEJA9bZS6+ec0ustFJKPgk7QFhBUck6GWydlkd5k=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: project-db-secret
      namespace: dwk-project
