---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: project-secret
  namespace: dwk-project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBmE93g68rGYEAm3DQm6OdQC97av79XP7cBhHghLiCVorKETh3vvrSVflL8QNFeairRJfDvF0kKq2wGLeU7/uLQCcZM+530lmDXfxzcOHpLhUheBBZsROmSAf/oe8OHkxUyhBl2POC3DvWbBdu+wFzQPMMpCbMBuSWxLDGAj949OTAWw9eiyrLkY0Xh/p7MVZ4M7iGTEUIXehV83INVL6rlWtClrvNWfcXBkXFTjQUWmnuXjSpqB7WhP0pPc2e4JpBh6kAedin9XqM2etGzkSKDdCmR/I4Sr7NYCQcmIQxLB+q+Rnt366ue7lNStPP1ckbreHrPLSW51wkGP4LgqKVUqbCFB9Gfkm/vratJ6g9vnDb8eoZ6UQeEVa0FAPKq3ki+m7/ctQjFJ6auowgRH11Xi4mtsbdP6DsAwXmYd51m8koL9Ql6eyilhPYWGt1vUy9SvnFStLb/JejNp1rZOPvYf1hvVLTqioghKNo8zcAEetwXP/wQADXJDPNzUhn1NjN7w/+7BLp3R7z2xyvtbkQb1IYgqGJf6cfWdhQEAdTwR87bRDd3nVC+bX2JJGJQnwX/t+i96q8OchhT1OHryZQvZ73GVLQq54TBh18S8IZ/bw9jqgDtVU9oFCocxOJ8NZiJV7veQerbEgkEUb3zyZBQr/UUzluXjJIlQhOzYdXSqm2XIQR6NrC41b3wM8hwrkRnkuvccXT7jghMj//xH4AWJDV535ioMG2mtmGoRJPkh5UJBxXMLB375MQhKFEcPmYGXMIsbEBsQA==
    TELEGRAM_BOT_TOKEN: AgArG3PiFtNNTq7lZGR2GPqSB20JVfl8FcToU2krvbOu3tVSMgxJt4J6BVkXrUo+x5X1MtGpooezwrtI5WtNqIrDlmhing5DBiCgCJ0XfzqjZS8ocIznQ7NrfVlWGTKomMd3qE+/F1unwLfrElt2ILA0JemqiiOyhlsEzjK1Itpw/XSKnFZPCl2e+sAh/nGE7rMfBnSuoCLPTx7Y9DFqjGK4GL2181/OtOoa9YnjpxrhH0l24aphB+vWHJUdjAYTomeLrPX+X732s4R/wQYn0ePYDdfJ/F3AzxY/71oqwdI1h/kSOeFiMZHJTNyd8LN+LWzhyF9D0ztVI9HzP5boorRb6t90Y0ukv4D1oaVb+sT8aj64u9gZMziReMHfNYToqpqx89xvS3Nd0sTICp+aBRYN3TXR2rlO/kgbB+JaAjCY18sXnR1pj6uwA3JlUNfq8yDphrvitmplouu9Ucxj1ZedFepObM6ZTLqNEEYbpJ81h02HWJBAN3n1h7wqnh0YWUAdfcie8P69VSmCpLr+V0IZ3/7DKXfijH8wHovp4mZrtUKx+ZqLMoY/6QUigU9z5Nt97bwvBewkQk+3Tsajzs7ThOdin5ApvncqlZ+PR35goQA+zWr+2xHepdBVc2THvKFkG+l9hTY7JV539UGNh9IaSe6EVFzc/5mQBAX/n0dbKtC3hz2W7DUPfd1AY8FvQDY6ecI5M+Ug+lIS6FV8qMFlwBHW1hhfH0SfmLnkrc5BBaM0vI7SH64PuCskqaKe
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: project-secret
      namespace: dwk-project
