apiVersion: v1
kind: Service
metadata:
  name: dwkproject-backend-svc
  namespace: dwk-project
spec:
  type: NodePort
  selector:
    app: dwkproject-backend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8000